##
# Server
##
server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on_param
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: /marketplace

##
# Spring and DataSource
##
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/marketplace_microservico2
    username: root
    password: 12345
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false

feign:
  client:
    config:
      usuarioClient:
        decode404: true
        loggerLevel: full
      produtoClient:
        decode404: true
        loggerLevel: full
      pagamentoClient:
        decode404: true
        loggerLevel: full